openapi: 3.0.3
info:
  title: Octagon openAPI
  description: This is Super-Super-Heroes' code platform
  version: 0.0.1
servers:
  - url: http://localhost:8080
paths:
  /users:
    post:
      tags:
        - users
      summary: Creates new user
      description: This endpoint for create a new user to Octagon. Request consists of user email, user first name, user last name and user password. Response may be consist of status code and response message
      requestBody:
        required: true
        description: Passes user data to create User
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/entities.User"
      responses:
        "201": { $ref: "#/components/responses/created" }
        "400": { $ref: "#/components/responses/badRequest" }
        "409": { $ref: "#/components/responses/conflict" }
        "500": { $ref: "#/components/responses/internalServerError" }
    get:
      tags:
        - users
      operationId: GetAllUsers
      parameters:
        - name: sort
          in: query
          description: Sorting options for result array that could be passed sequentially
          required: false
          schema:
            type: array
            items:
              type: string
              enum:
                - first_name
                - last_name
                - created_at
              default: first_name,last_name
            minItems: 1
            uniqueItems: true
          style: simple
        - name: offset
          in: query
          description: The number of items to skip before starting to collect the result set
          required: false
          schema:
            type: integer
            default: 0
        - name: limit
          in: query
          description: The numbers of items to return in result set
          required: false
          schema:
            type: integer
            default: NULL
      summary: Get list of users
      description: Retrieve not-sensitive data from users by given parameters
      responses:
        "200": { $ref: "#/components/responses/okResults" }
        "400": { $ref: "#/components/responses/badRequest"}
        "500": {$ref: "#/components/responses/internalServerError"}
  /users/{id}:
    get:
      summary: Return user
      description: The endpoint returns an user by the ID if the ID exists in the database.  Request consists of the ID specified in the url. Response consists of a status code and of a response body. The response body may consist an error message or an entity of rest.User
      responses:
        "200": { $ref: "#/components/responses/ok" }
        "400": { $ref: "#/components/responses/badRequest" }
        "404": { $ref: "#/components/responses/notFound" }
        "500": { $ref: "#/components/responses/internalServerError" }
    parameters:
      - name: id
        in: path
        description: ID of user to use
        required: true
        schema:
          type: array
          items:
            type: string
        style: simple

components:
  responses:
    ok:
      description: Success.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/rest.User"
    notFound:
      description: User not found.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    created:
      description: Successful created user.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/entities.User"
    badRequest:
      description: Bad Request.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    conflict:
      description: User provided email that already exists.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    internalServerError:
      description: Unexpected error.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    okResults:
      description: Successful users fetching
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UsersResponse"
  schemas:
    entities.User:
      type: object
      required:
        - email
        - first_name
        - last_name
        - password
      properties:
        email:
          {
            description: must contains '@' and must be unique,
            type: string,
            format: email,
            maxLength: 256,
            uniqueItems: true,
            example: john@email.com,
          }
        first_name: { type: string, example: John }
        last_name: { type: string, example: Doe }
        password:
          {
            description: only ASCII symbols,
            type: string,
            format: password,
            minLength: 8,
            maxLength: 256,
            example: "123456Aa",
          }
    rest.User:
      type: object
      required:
        - id
        - email
        - first_name
        - last_name
        - created_at
      properties:
        id: {
          description: unique identifier of the user entity ,
          type: string,
          format: id,
          uniqueItems: true,
          example: "297a80a4-ea77-4f9e-8d0c-ca03cb263625",
        }
        email:
          {
            description: must contains '@' and must be unique,
            type: string,
            format: email,
            maxLength: 256,
            uniqueItems: true,
            example: john@email.com,
          }
        first_name: { type: string, example: John }
        last_name: { type: string, example: Doe }
        created_at:
          {
            description: Indicates date and time of user creation,
            type: string,
            format: created_at,
            example: "2022-10-23T10:47:28.896701Z",
          }
    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
    UsersResponse:
      type: object
      required:
        - results
      properties:
        results:
          type: array
          items:
            $ref: "#/components/schemas/rest.User"
