openapi: 3.0.3
info:
  title: Octagon openAPI
  description: This is Super-Super-Heroes' code platform
  version: 0.0.1
servers:
  - url: http://localhost:8080
paths:
  /users:
    post:
      tags:
        - users
      summary: Creates new user
      description: This endpoint for create a new user to Octagon. Request consists of user email, user first name, user last name and user password. Response may be consist of status code and response message
      requestBody:
        required: true
        description: Passes user data to create User
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserRequest"
      responses:
        "201": { $ref: "#/components/responses/created" }
        "400": { $ref: "#/components/responses/badRequest" }
        "409": { $ref: "#/components/responses/conflict" }
        "500": { $ref: "#/components/responses/internalServerError" }
    delete:
      summary: Deletes user by ID
      description: For delete user by ID. Request should by consist of ID in UUID format. We use soft delete. Response should be consist of 204 status without body.
      requestBody:
        required: true
        description: Passes user ID to delete user.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeleteUserRequest"
      responses:
        "204": { $ref: "#/components/responses/noContent" }
        "400": { $ref: "#/components/responses/badRequest" }
        "404": { $ref: "#/components/responses/notFound" }
        "500": { $ref: "#/components/responses/internalServerError" }
  /users/{id}:
    get:
      summary: Return user
      description: The endpoint returns an user by the ID if the ID exists in the database.  Request consists of the ID specified in the url. Response consists of a status code and of a response body. The response body may consist an error message or an entity of PublicUser
      responses:
        "200": { $ref: "#/components/responses/ok" }
        "400": { $ref: "#/components/responses/badRequest" }
        "404": { $ref: "#/components/responses/notFound" }
        "500": { $ref: "#/components/responses/internalServerError" }
    parameters:
      - name: id
        in: path
        description: ID of user to use
        required: true
        schema:
          type: array
          items:
            type: string
        style: simple
components:
  responses:
    ok:
      description: Success.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PublicUserResponse"
    notFound:
      description: User not found.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    created:
      description: Successful created user.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CreateUserResponse"
    badRequest:
      description: Bad Request.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    conflict:
      description: User provided email that already exists.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    internalServerError:
      description: Unexpected error.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    noContent:
      description: User was deleted successfully. No content found.
  schemas:
    CreateUserRequest:
      type: object
      required:
        - email
        - first_name
        - last_name
        - password
      properties:
        email:
          {
            description: must contains '@' and must be unique,
            type: string,
            format: email,
            maxLength: 320,
            uniqueItems: true,
            example: john@email.com,
          }
        firstName: { type: string, example: John }
        lastName: { type: string, example: Doe }
        password:
          {
            description: only ASCII symbols,
            type: string,
            format: password,
            minLength: 8,
            maxLength: 256,
            example: "123456Aa",
          }
    DeleteUserRequest:
      type: object
      required:
        - ID
      properties:
        ID:
          {
            description: UUID,
            type: string,
            format: UUID,
            example: "c0f01e3a-2dc3-4ea2-8d99-893b443697f9",
          }
    PublicUserResponse:
      type: object
      required:
        - id
        - email
        - first_name
        - last_name
        - created_at
      properties:
        id:
          {
            description: unique identifier of the user entity,
            type: string,
            format: id,
            uniqueItems: true,
            example: "297a80a4-ea77-4f9e-8d0c-ca03cb263625",
          }
        email:
          {
            description: must contains '@' and must be unique,
            type: string,
            format: email,
            maxLength: 320,
            uniqueItems: true,
            example: john@email.com,
          }
        firstName: { type: string, example: John }
        lastName: { type: string, example: Doe }
        created_at:
          {
            description: Indicates date and time of user creation,
            type: string,
            format: created_at,
            example: "2022-10-23T10:47:28.896701Z",
          }
    CreateUserResponse:
      type: object
      required:
        - ID
      properties:
        ID:
          {
            description: UUID,
            type: string,
            format: UUID,
            example: "c0f01e3a-2dc3-4ea2-8d99-893b443697f9",
          }
    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string